---

# Ubuntu Playbook
- name: Ubuntu Playbook
  hosts: ubuntu

  tasks:
  - name: Update and Upgrade Repos
    apt:
      upgrade: dist
      update_cache: yes


# CentOS7 Playbook

- name: CentOS7 Playbook
  hosts: centos

  tasks:
  - name: Update and Upgrade Repos
    yum:
      name: "*"

# Web Servers Playbook

- name: Identify the OS Family and Install Apache Server Playbook
  hosts: web_servers

  tasks:
  - name: Identify the OSes
    debug: var=ansible_os_family
  
  - name: Read the vars from files
    include_vars: "{{lookup('first_found',params)}}"
    vars:
      params:
        files:
          - "vars/apache_{{ansible_os_family}}.yaml"

  - name: Installation Apache Server on the group named [web_server]
    ansible.builtin.package:
      name:
        - "{{apache_srv}}"
        - "{{php_lib}}"
      state: latest

- name: Add Ports and Reload Firewall on the group centos Playbook
  hosts: centos
  become: yes
  vars_files:
    - vars/http_https_port.yaml
  tags: firewall-playbook

  tasks:
    - name: Add HTTP Port to Firewall Declared in the http_https_port file
      firewalld:
        port: "{{http}}/tcp"
        permanent: true
        state: enabled
      register: ports_added_to_firewalld
      
    - name: Add the HTTPS Port Declared in the http_https_port file to Firewall
      firewalld:
        port: "{{https}}/tcp"
        permanent: true
        state: enabled
      register: ports_added_to_firewalld

    - name: Print Ports Added
      debug:
        var: ports_added_to_firewalld

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

- name: Add Ports and Reload UFW on the group ubuntu Playbook
  hosts: ubuntu
  become: yes
  vars_files:
    - vars/http_https_port.yaml
  tags: ufw-playbook

  tasks:
    - name: Add HTTP Port to UFW Declared in the http_https_port file
      ufw:
        port: "{{http}}"
        proto: tcp
        rule: allow
      register: ports_added_to_ufw

  tasks:
    - name: Add HTTPS Port to UFW Declared in the http_https_port file
      ufw:
        port: "{{https}}"
        proto: tcp
        rule: allow
      register: ports_added_to_ufw

    - name: Reload UFW
      ansible.builtin.service:
        name: ufw
        state: restarted

    - name: Copy the index file to the web servers
      copy:
        src: "{{project_dir}}"
        dest: "{{dest_dir}}"
        owner: root
        group: root
        mode: 0644
      tags:  copy_index_file